import ApolloClient, { createNetworkInterface } from 'apollo-client';
import { SubscriptionClient, addGraphQLSubscriptions } from 'subscriptions-transport-ws';

const wsClient = new SubscriptionClient('ws://localhost:4010/graphql-ws', {
  reconnect: true,
  connectionParams: {
    bearer: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJtaWRkbGVOYW1lIjpudWxsLCJhbGciOiJSUzI1NiIsImVtYWlsIjoidHdhbi5jb2VucmFhZEBuZWRhcC5jb20iLCJhdWQiOiJodHRwczpcL1wvcGVwbGluay5uZXQiLCJzdWIiOiJQZXBLZXl8MzUiLCJpc3MiOiJQZXBLZXkiLCJ1aWQiOjM1LCJleHAiOjE1Mzk0MTY4ODQsImZpcnN0TmFtZSI6IlR3YW4iLCJwcmVmZXJyZWRMYW5ndWFnZSI6Im5sLU5MIiwibG9naW4iOiJ0d2FuLmNvZW5yYWFkIiwibGFzdE5hbWUiOiJDb2VucmFhZCIsImlkIjozNSwiaWF0IjoxNTM2ODI0ODg0fQ.fM9sP-QO2_ZhaY33py-XwTYgr0IxE2A5oQbGNLDOp3J5h3JRuFtrLd15vi16Mpg44aody4qPxF4kBSNXkrGORy2B6fmJ7rUjkH-uhC4ZLpf4vY3Rx4_t1KVL_oBlMkc0Lx7_KJ0tJ_XEWImHX1KscZMclj4OfGKLzrixw3QcyFCaat0IhWnb1DMs0iFUD4VZk1FrD_ewQklPBPS2PxQhd9A06WaCFATpO4MGK3rlvGR9qFJ-AoY8-vISYs8URHfTKCg1KyAFCXlWq8_KD3zXJ4TARmYoxNEqtPoKj1eDcOHXAPmz7nDBs3Vtk8DqdfqsnWUvDzP7IKoXSdQ6WkbnDA"
  }
});

const baseNetworkInterface = createNetworkInterface('http://localhost:4010/graphql', {
  headers: {
    "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJtaWRkbGVOYW1lIjpudWxsLCJhbGciOiJSUzI1NiIsImVtYWlsIjoidHdhbi5jb2VucmFhZEBuZWRhcC5jb20iLCJhdWQiOiJodHRwczpcL1wvcGVwbGluay5uZXQiLCJzdWIiOiJQZXBLZXl8MzUiLCJpc3MiOiJQZXBLZXkiLCJ1aWQiOjM1LCJleHAiOjE1Mzk0MTY4ODQsImZpcnN0TmFtZSI6IlR3YW4iLCJwcmVmZXJyZWRMYW5ndWFnZSI6Im5sLU5MIiwibG9naW4iOiJ0d2FuLmNvZW5yYWFkIiwibGFzdE5hbWUiOiJDb2VucmFhZCIsImlkIjozNSwiaWF0IjoxNTM2ODI0ODg0fQ.fM9sP-QO2_ZhaY33py-XwTYgr0IxE2A5oQbGNLDOp3J5h3JRuFtrLd15vi16Mpg44aody4qPxF4kBSNXkrGORy2B6fmJ7rUjkH-uhC4ZLpf4vY3Rx4_t1KVL_oBlMkc0Lx7_KJ0tJ_XEWImHX1KscZMclj4OfGKLzrixw3QcyFCaat0IhWnb1DMs0iFUD4VZk1FrD_ewQklPBPS2PxQhd9A06WaCFATpO4MGK3rlvGR9qFJ-AoY8-vISYs8URHfTKCg1KyAFCXlWq8_KD3zXJ4TARmYoxNEqtPoKj1eDcOHXAPmz7nDBs3Vtk8DqdfqsnWUvDzP7IKoXSdQ6WkbnDA"
  }
});

const subscriptionNetworkInterface = addGraphQLSubscriptions(baseNetworkInterface, wsClient);

export default new ApolloClient({
  networkInterface: subscriptionNetworkInterface,
  connectToDevTools: true,
});
